name: osumpi
description: Analyze and manage your bakecode ecosystem with osumpi.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bsi_dart:
    git: https://github.com/osumpi/bsi-dart.git
  community_material_icon: ^5.9.55
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  material_floating_search_bar: ^0.3.4
  meta: ^1.3.0
  split_view: ^3.1.0
  fhir_yaml: ^0.5.2
  file: ^6.1.2
  file_picker: ^4.3.0
  flutter_animator: ^3.2.0
  flutter_colorpicker: ^1.0.3
  flutter_json_viewer: ^1.0.1
  flutter_riverpod: ^1.0.3
  glob: ^2.0.0
  json2yaml: ^3.0.0
  json_theme:
    git: https://github.com/peiffer-innovations/json_theme.git
  osumlog:
    git:
      https://github.com/osumpi/osumlog.git
  path: ^1.8.0
  pretty_json: ^2.0.0
  recase: ^4.0.0
  watcher: ^1.0.1
  yaml: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
