name: osumpi
description: Analyze and manage your bakecode ecosystem with osumpi.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bsi_dart:
    git: https://github.com/osumpi/bsi-dart.git

  community_material_icon: ^5.9.55
  flutter:
    sdk: flutter

  google_fonts: ^2.1.0
  material_floating_search_bar: ^0.3.4
  meta: ^1.3.0
  provider: ^5.0.0
  split_view: ^3.1.0

dev_dependencies:
  lint: ^1.5.3

flutter:
  uses-material-design: true
